services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dev
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  dev: